#!/usr/bin/env python3
"""genperm.py - emit a probe .c holding every single-statement
RELOCATION of a base statement list.

This is the lever matching/campaign/README.md found to be the one that
actually breaks gcc 2.9 ties (its stmtperm.py); this is the same idea
sized for vary.py, so a whole neighbourhood is scored in one build.

    python3 genperm.py > src/probe_rotx2.c
"""
import sys

PRE = '''/* generated by genperm.py - single-statement relocations of the
 * MatrixDrive_RotX (0x230198) assignment block.
 * Sweep: python3 vary.py src/probe_rotx2.c 0x230198 0xc8 */
typedef float FMATRIX[4][4];
extern FMATRIX mtxStack[];
extern int mtxSp;
extern void *memset();
extern void sceVu0MulMatrix(FMATRIX, FMATRIX, FMATRIX);
extern float MatrixDrive_Sin(short);
extern float MatrixDrive_Cos(short);
'''

STMTS = [
    "m[0][0]=one;",
    "m[1][0]=0.0f;",
    "m[1][1]=c;",
    "m[1][2]=s;",
    "m[1][3]=0.0f;",
    "m[2][0]=0.0f;",
    "m[2][1]=-s;",
    "m[2][2]=c;",
    "m[2][3]=0.0f;",
]

# base order; override on the command line, e.g.
#   python3 genperm.py 1,4,5,8,0,3,6,7,2
BASE = [1, 4, 5, 8, 0, 2, 3, 6, 7]
if len(sys.argv) > 1:
    BASE = [int(x) for x in sys.argv[1].split(",")]


def emit(name, order):
    body = "\n\t".join(STMTS[i] for i in order)
    return ('''void %s(short a){FMATRIX m; float c,s,one;
	c=MatrixDrive_Cos(a); one=1.0f; s=MatrixDrive_Sin(a);
	memset(m[0],0,16);
	%s
	memset(m[3],0,16); m[3][3]=one;
	sceVu0MulMatrix(mtxStack[mtxSp],mtxStack[mtxSp],m);}
''' % (name, body))


def main():
    out = [PRE]
    n = 0
    seen = set()
    for i in range(len(BASE)):
        for j in range(len(BASE) + 1):
            o = BASE[:]
            v = o.pop(i)
            o.insert(j if j <= i else j - 1, v)
            k = tuple(o)
            if k in seen:
                continue
            seen.add(k)
            out.append(emit("p%02d" % n, o))
            n += 1
    sys.stdout.write("".join(out))
    sys.stderr.write("genperm: %d variants\n" % n)


if __name__ == "__main__":
    main()
